steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$_PROJECT/jupyter:networking', '-f', './networking-notebook/Dockerfile', './networking-notebook']
images:
- 'gcr.io/$_PROJECT/jupyter:networking'
